# TSMC stock data
expected_data_tsmc = {
    "stock_code": "2330",
    "match_time": {
        "hours": 9,
        "Minutes": 4,
        "Seconds": 15,
        "Milliseconds": 61,
        "Microseconds": 278,
    },
    "revelation_note": {
        "trade_available": True,
        "n_bid": 5,
        "n_ask": 3,
        "trade_only": False,
    },
    "price_limit_mark": {
        "trade": "normal",
        "bid": "normal",
        "ask": "normal",
        "price_trend": "normal",
    },
    "status_note": {
        "trial_calc_status": "normal",
        "delayed_opening": False,
        "delayed_closing": False,
        "matching_method": "aggregate",
    },
    "cumulative_volume": 16423,
    "trade_price": 99.50,
    "trade_volume": 1234,
    "buy_price_1": 99.50,
    "buy_volume_1": 250,
    "buy_price_2": 99.00,
    "buy_volume_2": 175,
    "buy_price_3": 98.50,
    "buy_volume_3": 477,
    "buy_price_4": 97.50,
    "buy_volume_4": 669,
    "buy_price_5": 97.00,
    "buy_volume_5": 125,
    "sell_price_1": 100.00,
    "sell_volume_1": 80,
    "sell_price_2": 100.50,
    "sell_volume_2": 675,
    "sell_price_3": 101.50,
    "sell_volume_3": 460,
}

expected_data_2002 = {
    "stock_code": "2002",
    "match_time": {
        "hours": 10,
        "Minutes": 27,
        "Seconds": 33,
        "Milliseconds": 165,
        "Microseconds": 41,
    },
    "revelation_note": {
        "trade_available": True,
        "n_bid": 5,
        "n_ask": 0,
        "trade_only": False,
    },
    "price_limit_mark": {
        "trade": "limit_up",
        "bid": "limit_up",
        "ask": "normal",
        "price_trend": "normal",
    },
    "status_note": {
        "trial_calc_status": "normal",
        "delayed_opening": False,
        "delayed_closing": False,
        "matching_method": "aggregate",
    },
    "cumulative_volume": 11921,
    "trade_price": 13.85,
    "trade_volume": 1921,
    "buy_price_1": 13.85,
    "buy_volume_1": 540,
    "buy_price_2": 13.80,
    "buy_volume_2": 230,
    "buy_price_3": 13.75,
    "buy_volume_3": 72,
    "buy_price_4": 13.70,
    "buy_volume_4": 69,
    "buy_price_5": 13.65,
    "buy_volume_5": 81,
}


expected_data_1504 = {
    "stock_code": "1504",
    "match_time": {
        "hours": 9,
        "Minutes": 50,
        "Seconds": 23,
        "Milliseconds": 271,
        "Microseconds": 534,
    },
    "revelation_note": {
        "trade_available": True,
        "n_bid": 0,
        "n_ask": 5,
        "trade_only": False,
    },
    "price_limit_mark": {
        "trade": "limit_down",
        "bid": "normal",
        "ask": "limit_down",
        "price_trend": "normal",
    },
    "status_note": {
        "trial_calc_status": "normal",
        "delayed_opening": False,
        "delayed_closing": False,
        "matching_method": "aggregate",
    },
    "cumulative_volume": 650,
    "trade_price": 11.50,
    "trade_volume": 17,
    "sell_price_1": 11.50,
    "sell_volume_1": 70,
    "sell_price_2": 11.55,
    "sell_volume_2": 35,
    "sell_price_3": 11.60,
    "sell_volume_3": 46,
    "sell_price_4": 11.65,
    "sell_volume_4": 28,
    "sell_price_5": 11.70,
    "sell_volume_5": 19,
}

expected_data_1301 = {
    "stock_code": "1301",
    "match_time": {
        "hours": 9,
        "Minutes": 45,
        "Seconds": 19,
        "Milliseconds": 33,
        "Microseconds": 17,
    },
    "revelation_note": {
        "trade_available": True,
        "n_bid": 0,
        "n_ask": 0,
        "trade_only": False,
    },
    "price_limit_mark": {
        "trade": "limit_up",
        "bid": "normal",
        "ask": "normal",
        "price_trend": "downward_trend",
    },
    "status_note": {
        "trial_calc_status": "normal",
        "delayed_opening": False,
        "delayed_closing": False,
        "matching_method": "aggregate",
    },
    "cumulative_volume": 1558,
    "trade_price": 33.50,
    "trade_volume": 0,
}
